//! The map itself, laid out for the session that will read it.

use std::fmt::{self, Display};

use super::text::{indent_rest, short};
use crate::map::domain::{ReviewMap, WORKING};

/// The map itself. Deliberately without the deactivated notes: this stays a
/// picture of the map rather than a picture of the map plus a work queue.
pub struct MapReport<'a> {
    pub map: &'a ReviewMap,
    pub behind: u32,
}

impl Display for MapReport<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let map = self.map;
        writeln!(f, "map for {} → {}", map.branch, map.base)?;

        let at = if map.generated_at == WORKING {
            "uncommitted work".to_string()
        } else {
            short(&map.generated_at)
        };
        match self.behind {
            0 => writeln!(f, "generated at {at}")?,
            1 => writeln!(f, "generated at {at} (1 commit behind HEAD)")?,
            n => writeln!(f, "generated at {at} ({n} commits behind HEAD)")?,
        }
        if let Some(parent) = &map.parent {
            writeln!(f, "derived from {}", short(parent))?;
        }

        if map.is_empty() {
            return writeln!(f, "\nThe map is empty — nothing has been mapped yet.");
        }

        for (i, block) in map.blocks().iter().enumerate() {
            writeln!(f, "\nblock {}  {}  \"{}\"", i + 1, block.slug, block.title)?;
            if !block.context.trim().is_empty() {
                writeln!(f, "  context: {}", indent_rest(&block.context, 4))?;
            }
            if !block.files.is_empty() {
                writeln!(f, "  files:")?;
                for file in &block.files {
                    writeln!(f, "    {}", file.path)?;
                    if let Some(note) = &file.note {
                        writeln!(f, "      note: {}", indent_rest(note, 8))?;
                    }
                    for note in &file.line_notes {
                        writeln!(
                            f,
                            "      lines {}: {}",
                            note.range,
                            indent_rest(&note.text, 8)
                        )?;
                    }
                }
            }
            let attached: Vec<_> = map.skim_for(&block.slug).collect();
            if !attached.is_empty() {
                writeln!(f, "  skim:")?;
                for entry in attached {
                    writeln!(f, "    {} — {}", entry.path, entry.reason)?;
                }
            }
        }

        let loose: Vec<_> = map.loose_skim().collect();
        if !loose.is_empty() {
            writeln!(f, "\nunassigned skim:")?;
            for entry in loose {
                writeln!(f, "  {} — {}", entry.path, entry.reason)?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::map::domain::{LineRange, Position};
    use crate::testing::slug;

    fn sample() -> ReviewMap {
        let mut m = ReviewMap::new("fix/bull-signing-handoff", "main", "a3f1e9c1234567");
        m.add_block(
            &slug("recover-link"),
            "Recover the Bull link before signing",
            "The first version created generic handoff abstractions.",
            Position::End,
        )
        .unwrap();
        m.add_file(
            &slug("recover-link"),
            "services/bull_acceptance.go",
            None,
            None,
        )
        .unwrap();
        m.add_line_note(
            &slug("recover-link"),
            "services/bull_acceptance.go",
            LineRange::new(82, 116).unwrap(),
            "Recovery only happens on a fresh transition.",
        )
        .unwrap();
        m.add_file(
            &slug("recover-link"),
            "services/controller.go",
            Some("The deletions are not an additional change.".into()),
            None,
        )
        .unwrap();
        m.add_skim("go.sum", "regenerated by the dependency change", None)
            .unwrap();
        m
    }

    fn render(map: &ReviewMap, behind: u32) -> String {
        MapReport { map, behind }.to_string()
    }

    #[test]
    fn the_map_renders_blocks_files_and_both_note_levels() {
        let out = render(&sample(), 2);
        assert!(out.contains("map for fix/bull-signing-handoff → main"));
        assert!(out.contains("generated at a3f1e9c (2 commits behind HEAD)"));
        assert!(out.contains("block 1  recover-link  \"Recover the Bull link before signing\""));
        assert!(out.contains("lines 82-116: Recovery only happens"));
        assert!(out.contains("note: The deletions are not an additional change."));
        assert!(out.contains("unassigned skim:"));
        assert!(out.contains("go.sum — regenerated by the dependency change"));
    }

    #[test]
    fn a_single_commit_behind_is_not_pluralised() {
        assert!(render(&sample(), 1).contains("(1 commit behind HEAD)"));
    }

    #[test]
    fn an_up_to_date_map_says_nothing_about_distance() {
        assert!(!render(&sample(), 0).contains("behind HEAD"));
    }

    #[test]
    fn skim_attached_to_a_block_renders_under_it_not_at_the_bottom() {
        let mut m = sample();
        m.add_skim(
            "controller_test.go",
            "only feeds the existing test",
            Some(slug("recover-link")),
        )
        .unwrap();
        let out = render(&m, 0);
        assert!(
            out.contains("  skim:\n    controller_test.go"),
            "expected the attached skim inside the block:\n{out}"
        );
        assert!(out.contains("unassigned skim:\n  go.sum"));
    }

    #[test]
    fn an_empty_map_says_so_instead_of_printing_nothing() {
        let m = ReviewMap::new("b", "main", "abc1234");
        assert!(render(&m, 0).contains("The map is empty"));
    }
}
