//! The map itself, laid out for the session that will read it.

use std::fmt::{self, Display};

use super::text::{indent_rest, short};
use crate::map::domain::{ReviewMap, WORKING};

/// The map itself. Deliberately without the deactivated notes: this stays a
/// picture of the map rather than a picture of the map plus a work queue.
pub struct MapReport<'a> {
    pub map: &'a ReviewMap,
    pub behind: u32,
}

impl Display for MapReport<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let map = self.map;
        writeln!(f, "map for {} → {}", map.branch, map.base)?;

        let at = if map.generated_at == WORKING {
            "uncommitted work".to_string()
        } else {
            short(&map.generated_at)
        };
        match self.behind {
            0 => writeln!(f, "generated at {at}")?,
            1 => writeln!(f, "generated at {at} (1 commit behind HEAD)")?,
            n => writeln!(f, "generated at {at} ({n} commits behind HEAD)")?,
        }
        if let Some(parent) = &map.parent {
            writeln!(f, "derived from {}", short(parent))?;
        }

        if map.is_empty() {
            return writeln!(f, "\nThe map is empty — nothing has been mapped yet.");
        }

        for (i, block) in map.blocks().iter().enumerate() {
            writeln!(f, "\nblock {}  {}  \"{}\"", i + 1, block.slug, block.title)?;
            if !block.context.trim().is_empty() {
                writeln!(f, "  context: {}", indent_rest(&block.context, 4))?;
            }
            if !block.files.is_empty() {
                writeln!(f, "  files:")?;
                for file in &block.files {
                    writeln!(f, "    {}", file.path)?;
                    if let Some(note) = &file.note {
                        writeln!(f, "      note: {}", indent_rest(note, 8))?;
                    }
                    for note in &file.line_notes {
                        writeln!(
                            f,
                            "      lines {}: {}",
                            note.range,
                            indent_rest(&note.text, 8)
                        )?;
                    }
                }
            }
            let attached: Vec<_> = map.skim_for(&block.slug).collect();
            if !attached.is_empty() {
                writeln!(f, "  skim:")?;
                for entry in attached {
                    writeln!(f, "    {} — {}", entry.path, entry.reason)?;
                }
            }
        }

        let loose: Vec<_> = map.loose_skim().collect();
        if !loose.is_empty() {
            writeln!(f, "\nunassigned skim:")?;
            for entry in loose {
                writeln!(f, "  {} — {}", entry.path, entry.reason)?;
            }
        }

        // One line, not the whole orphan report — that is `map derive`'s, and
        // printing it twice would teach the reader to skip both. But a command
        // called `show` that hides open work is a trap: a session reading the
        // state here would never learn there is any.
        match map.orphans().len() {
            0 => {}
            1 => writeln!(
                f,
                "\n1 line note is deactivated — run `farol map derive` to decide about it."
            )?,
            n => writeln!(
                f,
                "\n{n} line notes are deactivated — run `farol map derive` to decide about them."
            )?,
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::map::domain::{LineRange, Position};
    use crate::testing::slug;

    /// A map with every level of prose the report can print: block context,
    /// file note, line note, and skim both attached and loose.
    fn sample() -> ReviewMap {
        let mut m = ReviewMap::new("fix/retry-on-timeout", "main", "a3f1e9c1234567");
        m.add_block(
            &slug("retry-window"),
            "Bound the retry window",
            "The first version retried forever, which hid the timeout.",
            Position::End,
        )
        .unwrap();
        m.add_file(&slug("retry-window"), "src/retry.rs", None, None)
            .unwrap();
        m.add_line_note(
            &slug("retry-window"),
            "src/retry.rs",
            LineRange::new(82, 116).unwrap(),
            "The backoff resets only on a fresh attempt.",
        )
        .unwrap();
        m.add_file(
            &slug("retry-window"),
            "src/client.rs",
            Some("The deletions are not an additional change.".into()),
            None,
        )
        .unwrap();
        m.add_skim("Cargo.lock", "regenerated by the dependency change", None)
            .unwrap();
        m
    }

    fn render(map: &ReviewMap, behind: u32) -> String {
        MapReport { map, behind }.to_string()
    }

    #[test]
    fn the_map_renders_blocks_files_and_both_note_levels() {
        let out = render(&sample(), 2);
        assert!(out.contains("map for fix/retry-on-timeout → main"));
        assert!(out.contains("generated at a3f1e9c (2 commits behind HEAD)"));
        assert!(out.contains("block 1  retry-window  \"Bound the retry window\""));
        assert!(out.contains("lines 82-116: The backoff resets only"));
        assert!(out.contains("note: The deletions are not an additional change."));
        assert!(out.contains("unassigned skim:"));
        assert!(out.contains("Cargo.lock — regenerated by the dependency change"));
    }

    #[test]
    fn a_single_commit_behind_is_not_pluralised() {
        assert!(render(&sample(), 1).contains("(1 commit behind HEAD)"));
    }

    #[test]
    fn an_up_to_date_map_says_nothing_about_distance() {
        assert!(!render(&sample(), 0).contains("behind HEAD"));
    }

    #[test]
    fn skim_attached_to_a_block_renders_under_it_not_at_the_bottom() {
        let mut m = sample();
        m.add_skim(
            "src/retry_test.rs",
            "only feeds the existing test",
            Some(slug("retry-window")),
        )
        .unwrap();
        let out = render(&m, 0);
        assert!(
            out.contains("  skim:\n    src/retry_test.rs"),
            "expected the attached skim inside the block:\n{out}"
        );
        assert!(out.contains("unassigned skim:\n  Cargo.lock"));
    }

    #[test]
    fn an_empty_map_says_so_instead_of_printing_nothing() {
        let m = ReviewMap::new("b", "main", "abc1234");
        assert!(render(&m, 0).contains("The map is empty"));
    }

    #[test]
    fn a_map_of_uncommitted_work_says_so_instead_of_printing_a_sha() {
        // There is no commit to name, and a seven-character slice of the
        // sentinel would be gibberish.
        let mut m = sample();
        m.generated_at = crate::map::domain::WORKING.to_string();

        let out = render(&m, 0);

        assert!(out.contains("generated at uncommitted work"), "{out}");
    }

    #[test]
    fn a_block_with_no_context_prints_no_empty_field() {
        // A `context:` line with nothing after it reads as a mistake.
        let mut m = ReviewMap::new("feature/x", "main", "abc1234");
        m.add_block(&slug("bare"), "Just a heading", "", Position::End)
            .unwrap();

        let out = render(&m, 0);

        assert!(out.contains("bare"), "{out}");
        assert!(!out.contains("context:"), "{out}");
    }

    #[test]
    fn a_block_with_no_files_prints_no_empty_list() {
        let mut m = ReviewMap::new("feature/x", "main", "abc1234");
        m.add_block(&slug("bare"), "t", "c", Position::End).unwrap();

        assert!(!render(&m, 0).contains("files:"));
    }

    #[test]
    fn a_file_with_no_notes_of_any_kind_is_still_listed() {
        // It is in the block, so the reviewer has to read it; the map simply
        // has nothing extra to say about it.
        let mut m = ReviewMap::new("feature/x", "main", "abc1234");
        m.add_block(&slug("core"), "t", "c", Position::End).unwrap();
        m.add_file(&slug("core"), "quiet.rs", None, None).unwrap();

        let out = render(&m, 0);

        assert!(out.contains("quiet.rs"), "{out}");
        assert!(!out.contains("note:"), "{out}");
        assert!(!out.contains("lines "), "{out}");
    }

    #[test]
    fn a_deactivated_note_is_admitted_without_reprinting_the_whole_report() {
        // `show` hiding open work is a trap: a session reading the state here
        // would never learn there is any. But the full orphan report belongs to
        // `map derive`, and printing it in both places teaches the reader to
        // skim both.
        let mut m = sample();
        m.reanchor_notes(|_, _| {
            Ok::<_, crate::map::domain::MapError>(crate::map::domain::NoteFate::Orphan {
                snapshot: "if attempt.state == State::Pending {".into(),
                reason: crate::map::domain::OrphanReason::HunkOverlap,
            })
        })
        .unwrap();

        let out = render(&m, 0);

        assert!(out.contains("1 line note is deactivated"), "{out}");
        assert!(out.contains("farol map derive"), "{out}");
        assert!(
            !out.contains("code it covered"),
            "the snapshot belongs to the orphan report, not here:\n{out}"
        );
    }

    #[test]
    fn several_deactivated_notes_are_counted() {
        let mut m = sample();
        m.add_line_note(
            &slug("retry-window"),
            "src/retry.rs",
            LineRange::new(20, 22).unwrap(),
            "another",
        )
        .unwrap();
        m.reanchor_notes(|_, _| {
            Ok::<_, crate::map::domain::MapError>(crate::map::domain::NoteFate::Orphan {
                snapshot: String::new(),
                reason: crate::map::domain::OrphanReason::HunkOverlap,
            })
        })
        .unwrap();

        assert!(render(&m, 0).contains("2 line notes are deactivated"));
    }

    #[test]
    fn a_map_with_nothing_pending_says_nothing_about_it() {
        assert!(!render(&sample(), 0).contains("deactivated"));
    }
}
