use crate::diff::domain::ReviewPath;
use crate::map::application::MapEditor;
use crate::map::domain::{ReviewMap, Slug};
use crate::shared::error::Result;

/// Mark a file as safe to read diagonally, optionally next to the block that
/// caused it to change.
#[derive(Clone)]
pub struct AddSkim {
    maps: MapEditor,
}

impl AddSkim {
    pub fn new(maps: MapEditor) -> Self {
        Self { maps }
    }

    pub fn execute(
        &self,
        path: &ReviewPath,
        reason: &str,
        block: Option<Slug>,
    ) -> Result<ReviewMap> {
        self.maps
            .edit(|map| map.add_skim(path.as_str(), reason, block))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::{slug, use_case_setup, with_block};

    #[test]
    fn a_skim_entry_can_be_attached_to_the_block_that_caused_it() {
        let (svc, scope) = with_block(&["Cargo.lock"]);

        let map = AddSkim::new(svc.editor)
            .execute(
                &scope.path("Cargo.lock").unwrap(),
                "regenerated by the dependency change",
                Some(slug("core")),
            )
            .unwrap();

        assert_eq!(map.skim()[0].block.as_ref().map(Slug::as_str), Some("core"));
    }

    #[test]
    fn a_skim_entry_with_no_block_stands_on_its_own() {
        let (svc, scope) = use_case_setup(&["Cargo.lock"]);

        let map = AddSkim::new(svc.editor)
            .execute(&scope.path("Cargo.lock").unwrap(), "generated", None)
            .unwrap();

        assert!(map.skim()[0].block.is_none());
    }

    #[test]
    fn a_skim_entry_cannot_name_a_block_that_does_not_exist() {
        let (svc, scope) = use_case_setup(&["Cargo.lock"]);

        assert!(
            AddSkim::new(svc.editor)
                .execute(
                    &scope.path("Cargo.lock").unwrap(),
                    "generated",
                    Some(slug("nope")),
                )
                .is_err()
        );
    }
}
