use crate::diff::domain::ReviewPath;
use crate::map::application::MapEditor;
use crate::map::domain::{ReviewMap, Slug};
use crate::shared::error::Result;

/// Mark a file as safe to read diagonally, optionally next to the block that
/// caused it to change.
#[derive(Clone)]
pub struct AddSkim {
    maps: MapEditor,
}

impl AddSkim {
    pub fn new(maps: MapEditor) -> Self {
        Self { maps }
    }

    pub fn execute(
        &self,
        path: &ReviewPath,
        reason: &str,
        block: Option<Slug>,
    ) -> Result<ReviewMap> {
        self.maps
            .edit(|map| map.add_skim(path.as_str(), reason, block))
    }
}

#[derive(Clone)]
pub struct RemoveSkim {
    maps: MapEditor,
}

impl RemoveSkim {
    pub fn new(maps: MapEditor) -> Self {
        Self { maps }
    }

    pub fn execute(&self, path: &ReviewPath) -> Result<ReviewMap> {
        self.maps.edit(|map| map.remove_skim(path.as_str()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::map::application::AddBlock;
    use crate::map::domain::Position;
    use crate::testing::{slug, use_case_setup};

    #[test]
    fn a_skim_entry_can_be_attached_to_the_block_that_caused_it() {
        let (svc, scope) = use_case_setup(&["go.sum"]);
        let maps = svc.editor.clone();
        AddBlock::new(maps.clone())
            .execute(&slug("core"), "t", "c", Position::End, &[])
            .unwrap();

        let map = AddSkim::new(maps)
            .execute(
                &scope.path("go.sum").unwrap(),
                "regenerated by the dependency change",
                Some(slug("core")),
            )
            .unwrap();

        assert_eq!(map.skim[0].block.as_ref().map(Slug::as_str), Some("core"));
    }

    #[test]
    fn a_skim_entry_with_no_block_stands_on_its_own() {
        let (svc, scope) = use_case_setup(&["go.sum"]);
        let maps = svc.editor.clone();

        let map = AddSkim::new(maps)
            .execute(&scope.path("go.sum").unwrap(), "generated", None)
            .unwrap();

        assert!(map.skim[0].block.is_none());
    }

    #[test]
    fn a_skim_entry_cannot_name_a_block_that_does_not_exist() {
        let (svc, scope) = use_case_setup(&["go.sum"]);
        let maps = svc.editor.clone();

        assert!(
            AddSkim::new(maps)
                .execute(
                    &scope.path("go.sum").unwrap(),
                    "generated",
                    Some(slug("nope"))
                )
                .is_err()
        );
    }

    #[test]
    fn removing_takes_the_entry_back_out() {
        let (svc, scope) = use_case_setup(&["go.sum"]);
        let maps = svc.editor.clone();
        let path = scope.path("go.sum").unwrap();
        AddSkim::new(maps.clone())
            .execute(&path, "generated", None)
            .unwrap();

        let map = RemoveSkim::new(maps).execute(&path).unwrap();

        assert!(map.skim.is_empty());
    }
}
